In [16]:
import numpy as np

#étape 0 : definition du tableau

cat_id = [1, 6, 4, 8]

random_int = np.random.choice(cat_id, size=(15, 25))

random_int

print(random_int, random_int[0,0])

#étape 1 : transposer le tableau en affichant pygame

[[6 1 8 1 4 8 6 8 6 4 1 8 8 1 6 6 6 8 6 1 8 4 6 4 4]
 [1 1 8 8 8 8 6 8 6 8 4 1 4 4 8 8 1 4 6 6 4 8 4 6 8]
 [1 6 6 4 6 8 1 1 4 6 6 4 4 8 8 8 4 6 4 6 1 4 6 1 8]
 [8 4 6 1 4 6 4 6 8 1 6 1 6 6 6 1 6 6 8 4 4 1 8 8 1]
 [4 4 1 1 8 4 1 6 6 4 6 6 6 1 4 6 4 4 6 1 1 8 8 1 6]
 [8 6 4 8 8 4 6 1 4 4 1 6 4 6 8 6 6 4 4 6 4 1 1 4 1]
 [8 1 4 6 4 4 8 4 8 1 4 1 1 8 1 4 6 6 4 1 1 4 8 6 1]
 [8 6 1 4 4 6 8 1 1 6 1 6 6 1 4 8 6 4 1 8 6 8 4 1 8]
 [1 1 6 1 6 1 4 6 8 8 8 1 1 4 6 4 1 4 4 1 8 1 6 1 8]
 [6 4 1 8 6 1 8 6 8 4 8 1 1 8 6 4 4 6 4 4 4 6 8 4 6]
 [4 4 8 1 6 4 8 1 4 4 8 6 8 1 1 4 6 6 1 8 6 1 1 1 1]
 [6 4 1 1 4 1 8 8 8 4 6 8 1 4 8 6 1 4 4 4 8 8 6 8 8]
 [4 4 8 6 8 4 4 4 8 1 8 1 6 8 1 8 4 1 8 1 1 8 8 8 6]
 [6 6 4 8 4 1 6 1 8 1 1 8 6 4 8 1 1 8 4 8 8 1 4 4 8]
 [1 6 8 6 6 4 6 6 8 8 1 8 4 8 6 8 4 6 4 1 1 1 8 1 6]] 6
