In [3]:
import numpy as np

#étape 0 : definition du tableau

cat_id = [1, 6, 4, 8]

random_int = np.random.choice(cat_id, size=(15, 25))

random_int

print(random_int, random_int[0,0])

#étape 1 : transposer le tableau en affichant pygame

[[4 6 1 4 1 1 1 1 4 8 8 6 1 1 6 6 4 1 8 4 4 1 8 6 8]
 [1 8 8 6 4 4 1 4 4 6 4 4 1 8 1 1 8 4 6 4 8 1 6 6 1]
 [4 8 1 4 6 1 1 4 8 6 8 6 6 4 4 6 8 8 6 8 8 6 6 1 4]
 [1 1 8 4 4 6 1 1 8 6 1 6 4 6 1 6 6 4 6 4 4 8 4 8 8]
 [6 4 6 1 8 4 6 6 1 4 8 6 4 4 1 1 6 4 4 1 1 8 4 1 6]
 [1 4 6 6 4 8 1 4 8 6 6 1 1 4 6 6 1 6 8 8 1 1 1 8 6]
 [8 8 1 6 1 8 4 1 8 6 4 6 8 1 6 6 4 8 4 6 1 8 4 6 8]
 [6 8 6 4 8 6 4 8 1 4 6 4 8 1 4 6 4 6 4 4 4 1 6 4 6]
 [1 6 4 1 1 4 4 1 6 4 1 1 4 8 8 8 4 6 1 6 8 1 1 1 4]
 [6 8 1 4 4 4 6 8 8 1 6 8 4 6 4 1 1 1 6 1 4 1 4 8 6]
 [1 6 6 4 4 8 4 1 1 8 1 8 6 4 4 6 6 8 4 8 6 1 1 6 8]
 [4 8 1 6 8 1 8 4 6 8 6 6 1 4 6 4 6 1 8 4 1 6 1 1 6]
 [4 4 8 6 4 4 1 6 4 8 6 1 8 4 8 8 1 4 1 6 6 6 1 4 8]
 [4 8 1 8 6 1 4 4 4 1 4 6 8 6 6 6 6 6 4 1 4 1 1 1 6]
 [1 4 1 1 4 1 1 4 6 4 6 4 1 6 1 8 4 1 1 8 6 8 4 1 8]] 4


In [4]:
import pandas as pd
df = pd.read_csv('triv_ia_dlc.csv')

# def question(categorie: str):
#     colone_question = df['question'] 
#     print (colone_question)



df



FileNotFoundError: [Errno 2] No such file or directory: 'triv_ia_dlc.csv'

In [ ]:


game_board = np.zeros((15, 25))


#definition d'un cercle dans le game_board avec des 1
game_board[0,0] = 1
game_board[0,0] = 1
game_board[0,0] = 1

game_board

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [ ]:
# Réinitialiser le tableau à zéro
game_board = np.zeros((15, 25))

# Définir manuellement les indices pour former un cercle approximatif
# Cela est fait par approximation en raison de la grille discrète
bord_sup = [
    (1, 6), (1, 7), (1, 8), (1, 9), (1, 10), (1, 11), (1, 12), (1, 13)
]

bord_inf = [
    (13, 6), (13, 7), (13, 8), (13, 9), (13, 10), (13, 11), (13, 12), (13, 13)
]

# Mettre à jour le tableau pour former un cercle
for y, x in bord_sup:
    game_board[y, x] = 1
for y, x in bord_inf:
    game_board[y, x] = 1

game_board


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 

In [ ]:
import numpy as np

game_board = np.random.choice(cat_id, size=(15, 25))